# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Develop run server
    init: >
      npm install &&
      gp sync-done npminstall
    command: npm run start-server
  - name: Unit Tests
    init: gp sync-await npminstall
    command: npm run test
  - name: Build SPA
    init: >
      gp sync-await npminstall &&
      cd spa &&
      npm install
    command: >
      cd spa &&
      npm run build
  - name: Develop run SPA
    init: gp sync-await npminstall
    command: >
      cd spa &&
      npm start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
